/// Anticipated Workspace — Phase 0b.
/// Surfaces the single most actionable episode (Precise preferred, Broad fallback)
/// Only renders when at least one episode exists.
/// Connects Episode Detector output to Panel C's template system (episode-scoped).

import { useState, useEffect, useRef } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { Episode, TrustStateView, TrustStateEnum } from "../types";
import { CATEGORY_TEMPLATES } from "../templates";
import { SynthesisView } from './SynthesisView';
import { useSynthesis, SynthesisPayload } from '../hooks/useSynthesis';
import { mapCategoryToSynthesisType, canSynthesize } from '../utils/synthesisCategory';

const COOLDOWN_MS = 90_000;

interface Props {
  episodes: Episode[];
}

export function AnticipatedWorkspace({ episodes }: Props) {
  const [trustState, setTrustState] = useState<TrustStateEnum | null>(null);
  const [redirectNote, setRedirectNote] = useState(false);
  const [wasAutoGenerated, setWasAutoGenerated] = useState(false);

  const lastAutoGenerateRef = useRef<number>(0);
  const pendingTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    invoke<TrustStateView>('get_trust_state')
      .then(v => setTrustState(v.current_state))
      .catch(() => null);
  }, []);

  function latestCapture(ep: Episode): number {
    return Math.max(...ep.resources.map(r => r.captured_at), 0);
  }

  const sortedEpisodes = [...episodes].sort(
    (a, b) => latestCapture(b) - latestCapture(a)
  );

  const bestPrecise = sortedEpisodes.find(e => e.mode === "Precise");
  const bestBroad   = sortedEpisodes.find(e => e.mode === "Broad");

  let ep: Episode | undefined;
  if (bestPrecise && bestBroad) {
    ep = latestCapture(bestPrecise) >= latestCapture(bestBroad)
      ? bestPrecise
      : bestBroad;
  } else {
    ep = bestPrecise ?? bestBroad;
  }

  // useSynthesis debe llamarse antes de cualquier return condicional (regla de hooks).
  // anchorKey vacío cuando no hay episodio — el hook queda inerte.
  const synthesisAnchorKey = ep?.episode_id ?? '';
  const { state: synthState, generate: synthGenerate, generateIfIdle } = useSynthesis(synthesisAnchorKey);

  const category = ep?.resources[0]?.category ?? 'otro';
  const synthesisType = mapCategoryToSynthesisType(category);

  // Payload estable construido con los datos del episodio actual
  const synthesisPayload: SynthesisPayload | null = ep && synthesisType ? {
    category,
    titles:        ep.resources.map(r => r.title),
    domains:       ep.resources.map(r => r.domain),
    synthesisType,
    anchorType:    'session',
  } : null;

  // T4 — Auto-síntesis en Autonomous con cooldown 90s.
  // Solo si no hay ya síntesis persistida (generateIfIdle lo detecta vía stateRef).
  // Acción manual (botón Generar/Regenerar) siempre ignora el cooldown.
  useEffect(() => {
    if (trustState !== 'Autonomous' || !ep || !synthesisPayload || !canSynthesize(category)) {
      return;
    }

    function maybeAutoGenerate() {
      const now = Date.now();
      if (now - lastAutoGenerateRef.current < COOLDOWN_MS) {
        if (pendingTimerRef.current) clearTimeout(pendingTimerRef.current);
        const remaining = COOLDOWN_MS - (now - lastAutoGenerateRef.current);
        pendingTimerRef.current = setTimeout(maybeAutoGenerate, remaining);
        return;
      }
      lastAutoGenerateRef.current = now;
      setWasAutoGenerated(true);
      generateIfIdle(synthesisPayload!);
    }

    maybeAutoGenerate();

    return () => {
      if (pendingTimerRef.current) {
        clearTimeout(pendingTimerRef.current);
        pendingTimerRef.current = null;
      }
    };
  // Dispara cuando cambia el episodio activo o cuando se entra en Autonomous
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ep?.episode_id, trustState]);

  // Resetear indicador auto-generado cuando cambia el episodio
  useEffect(() => {
    setWasAutoGenerated(false);
  }, [ep?.episode_id]);

  if (!ep) return null;

  const actions = (CATEGORY_TEMPLATES[category] ?? CATEGORY_TEMPLATES.otro).slice(0, 3);
  const preview = ep.resources.slice(0, 3);
  const extra = ep.resources.length - preview.length;

  // Defensa en profundidad (D25): si consent falta al pulsar Generar en Trusted,
  // redirige al Privacy Dashboard en lugar de intentar grabar consent aquí.
  async function handleGenerateRequest() {
    const consent = await invoke<{ has_consent: boolean }>('check_synthesis_consent');
    if (!consent.has_consent) {
      setRedirectNote(true);
      throw new Error('consent needed');
    }
  }

  return (
    <section className="anticipated-workspace" aria-label="Workspace anticipatorio">
      <div className="anticipated-workspace__badge-row">
        <span className="anticipated-workspace__badge">Próxima tarea</span>
        <span className="anticipated-workspace__label">{ep.label}</span>
        <span className="anticipated-workspace__meta">
          {ep.resources.length} recursos · {Math.round(ep.coherence * 100)}% coherencia
        </span>
      </div>

      <div className="anticipated-workspace__body">
        <div className="anticipated-workspace__resources">
          {preview.map((r) => (
            <span key={r.uuid} className="anticipated-workspace__resource-chip">
              <span className="anticipated-workspace__chip-icon">
                {r.domain.charAt(0).toUpperCase()}
              </span>
              <span className="anticipated-workspace__chip-title">{r.title}</span>
            </span>
          ))}
          {extra > 0 && (
            <span className="anticipated-workspace__resource-chip anticipated-workspace__resource-chip--more">
              +{extra} más
            </span>
          )}
        </div>

        <ul className="anticipated-workspace__actions">
          {actions.map((action, i) => {
            const id = `aw-action-${ep!.episode_id}-${i}`;
            return (
              <li key={id} className="anticipated-workspace__action">
                <input
                  type="checkbox"
                  id={id}
                  className="anticipated-workspace__checkbox"
                />
                <label htmlFor={id} className="anticipated-workspace__action-label">
                  {action}
                </label>
              </li>
            );
          })}
        </ul>
      </div>

      {redirectNote && (
        <p className="anticipated-workspace__redirect-note">
          Para activar la síntesis, ve al Panel de Privacidad (🔒) y activa el toggle.
        </p>
      )}

      {(trustState === 'Trusted' || trustState === 'Autonomous') && synthesisType !== null && (
        <SynthesisView
          anchorType="session"
          category={category}
          synthesisType={synthesisType}
          titles={ep.resources.map(r => r.title)}
          domains={ep.resources.map(r => r.domain)}
          state={synthState}
          generate={synthGenerate}
          wasAutoGenerated={wasAutoGenerated}
          onRequest={trustState === 'Trusted' ? handleGenerateRequest : undefined}
        />
      )}
    </section>
  );
}
