import { useCallback, useState } from 'react';
import { renderMarkdown } from '../utils/renderMarkdown';
import { SynthesisStatus, SynthesisPayload } from '../hooks/useSynthesis';

interface SynthesisViewProps {
  anchorType: 'pattern' | 'session';
  category: string;
  synthesisType: string;
  titles: string[];
  domains: string[];
  // Estado y generate gestionados externamente (por AnticipatedWorkspace o EpisodePanel)
  state: SynthesisStatus;
  generate: (payload: SynthesisPayload) => Promise<void>;
  // T5: indica que la síntesis fue auto-generada (Autonomous)
  wasAutoGenerated?: boolean;
  // onRequest presente → Trusted (botón manual + consent check). Ausente → Autonomous.
  onRequest?: () => Promise<void>;
}

export function SynthesisView(props: SynthesisViewProps) {
  const {
    anchorType, category, synthesisType, titles, domains,
    state, generate, wasAutoGenerated, onRequest,
  } = props;
  const [copied, setCopied] = useState(false);

  const handleGenerate = useCallback(async () => {
    await generate({ category, titles, domains, synthesisType, anchorType });
  }, [generate, category, titles, domains, synthesisType, anchorType]);

  async function copyToClipboard(content: string) {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function exportMarkdown(content: string) {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `synthesis-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  if (state.status === 'idle') {
    if (onRequest === undefined) return null;
    return (
      <div className="synthesis-view synthesis-view--idle">
        <button className="synthesis-view__generate" onClick={async () => {
          await onRequest();
          handleGenerate();
        }}>
          Generar síntesis
        </button>
      </div>
    );
  }

  if (state.status === 'loading') {
    return (
      <div className="synthesis-view synthesis-view--loading">
        <p>Generando síntesis…</p>
      </div>
    );
  }

  if (state.status === 'streaming') {
    return (
      <div className="synthesis-view synthesis-view--streaming">
        <div
          className="synthesis-view__content"
          dangerouslySetInnerHTML={{ __html: renderMarkdown(state.content) }}
        />
      </div>
    );
  }

  if (state.status === 'complete') {
    const dateLabel = state.generatedAt
      ? `Generada el ${new Date(state.generatedAt * 1000).toLocaleDateString('es-ES', {
          day: 'numeric', month: 'short', year: 'numeric',
        })}`
      : null;
    return (
      <div className="synthesis-view synthesis-view--complete">
        {wasAutoGenerated && (
          <span className="synthesis-view__auto-flag">Generada automáticamente</span>
        )}
        <div
          className="synthesis-view__content"
          dangerouslySetInnerHTML={{ __html: renderMarkdown(state.content) }}
        />
        <p className="synthesis-view__disclaimer">
          Síntesis generada por IA. La información puede contener errores.
          Verifica datos críticos antes de tomar decisiones.
        </p>
        <div className="synthesis-view__actions">
          <button
            className="synthesis-view__copy"
            onClick={() => copyToClipboard(state.content)}
          >
            {copied ? '¡Copiado!' : 'Copiar'}
          </button>
          <button
            className="synthesis-view__export"
            onClick={() => exportMarkdown(state.content)}
          >
            Exportar Markdown
          </button>
          {onRequest !== undefined && (
            <button className="synthesis-view__regenerate" onClick={handleGenerate}>
              Regenerar
            </button>
          )}
        </div>
        {dateLabel && (
          <p className="synthesis-view__date">{dateLabel}</p>
        )}
      </div>
    );
  }

  // error
  return (
    <div className="synthesis-view synthesis-view--error">
      <p className="synthesis-view__error">{state.message}</p>
      {onRequest !== undefined && (
        <button className="synthesis-view__retry" onClick={handleGenerate}>
          Reintentar
        </button>
      )}
    </div>
  );
}
