use rusqlite::{Connection, Result, params};
use serde::{Deserialize, Serialize};
use std::path::Path;

// ── Privacy Dashboard types (Phase 0b, D14) ──────────────────────────────────

#[derive(Debug, Serialize)]
pub struct CategoryCount {
    pub category: String,
    pub count: i64,
}

#[derive(Debug, Serialize)]
pub struct DomainCount {
    pub domain: String,
    pub count: i64,
}

/// Aggregate stats exposed by the Privacy Dashboard.
/// Only domain and category fields are used — url/title stay encrypted (D1).
#[derive(Debug, Serialize)]
pub struct PrivacyStats {
    pub resource_count: i64,
    pub categories: Vec<CategoryCount>,
    pub domains: Vec<DomainCount>,
}

/// A single bookmark resource as stored in SQLCipher.
/// Fields match the schema defined in TS-0a-007.
/// url and title are stored encrypted; domain and category are stored in clear (D1).
/// captured_at: Unix timestamp (seconds). 0 for bootstrap imports without a timestamp.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Resource {
    pub id: i64,
    pub uuid: String,
    pub url: String,
    pub title: String,
    pub domain: String,
    pub category: String,
    pub captured_at: i64,
}

/// A resource ready to be inserted — no id yet, uuid generated by caller.
#[derive(Debug, Deserialize)]
pub struct NewResource {
    pub uuid: String,
    pub url: String,
    pub title: String,
    pub domain: String,
    pub category: String,
    pub captured_at: i64,
}

pub struct Db {
    conn: Connection,
}

impl Db {
    /// Open (or create) the encrypted SQLCipher database at the given path.
    /// key is the passphrase used for AES encryption; it never leaves this process.
    pub fn open(path: &Path, key: &str) -> Result<Self> {
        let conn = Connection::open(path)?;
        conn.execute_batch(&format!("PRAGMA key = '{key}';"))?;
        conn.execute_batch("PRAGMA journal_mode = WAL;")?;
        Ok(Self { conn })
    }

    /// Create the `resources` table and its UUID index if they do not exist.
    /// Adds captured_at column for Phase 0b Session Builder (migration-safe).
    pub fn migrate(&self) -> Result<()> {
        // Create table with full 0b schema for new installs.
        self.conn.execute_batch("
            CREATE TABLE IF NOT EXISTS resources (
                id          INTEGER PRIMARY KEY,
                uuid        TEXT    NOT NULL,
                url         TEXT    NOT NULL,
                title       TEXT    NOT NULL,
                domain      TEXT    NOT NULL,
                category    TEXT    NOT NULL,
                captured_at INTEGER NOT NULL DEFAULT 0
            );
            CREATE UNIQUE INDEX IF NOT EXISTS idx_resources_uuid ON resources(uuid);
        ")?;
        // Add captured_at to existing 0a databases. Silently ignore if already present.
        let _ = self.conn.execute_batch(
            "ALTER TABLE resources ADD COLUMN captured_at INTEGER NOT NULL DEFAULT 0;"
        );
        Ok(())
    }

    /// Insert a new resource. url and title must already be encrypted by the caller.
    pub fn insert_resource(&self, r: &NewResource) -> Result<i64> {
        self.conn.execute(
            "INSERT INTO resources (uuid, url, title, domain, category, captured_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            params![r.uuid, r.url, r.title, r.domain, r.category, r.captured_at],
        )?;
        Ok(self.conn.last_insert_rowid())
    }

    /// Insert a resource, ignoring if the UUID already exists.
    /// Returns true if inserted, false if skipped (duplicate UUID).
    pub fn insert_or_ignore(&self, r: &NewResource) -> Result<bool> {
        let n = self.conn.execute(
            "INSERT OR IGNORE INTO resources (uuid, url, title, domain, category, captured_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            params![r.uuid, r.url, r.title, r.domain, r.category, r.captured_at],
        )?;
        Ok(n > 0)
    }

    /// Return all resources ordered by captured_at, then id.
    pub fn all_resources(&self) -> Result<Vec<Resource>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, uuid, url, title, domain, category, captured_at
             FROM resources ORDER BY captured_at, id",
        )?;
        let rows = stmt.query_map([], |row| {
            Ok(Resource {
                id: row.get(0)?,
                uuid: row.get(1)?,
                url: row.get(2)?,
                title: row.get(3)?,
                domain: row.get(4)?,
                category: row.get(5)?,
                captured_at: row.get(6)?,
            })
        })?;
        rows.collect()
    }

    /// Update the category of a resource identified by uuid.
    /// Used by the Classifier (T-0a-003) after domain classification.
    pub fn set_category(&self, uuid: &str, category: &str) -> Result<usize> {
        self.conn.execute(
            "UPDATE resources SET category = ?1 WHERE uuid = ?2",
            params![category, uuid],
        )
    }

    /// Return the number of stored resources.
    pub fn count(&self) -> Result<i64> {
        self.conn.query_row(
            "SELECT COUNT(*) FROM resources",
            [],
            |row| row.get(0),
        )
    }

    /// Return aggregate stats for the Privacy Dashboard.
    /// Queries only domain and category columns (in clear per D1).
    pub fn privacy_stats(&self) -> Result<PrivacyStats> {
        let resource_count: i64 = self.conn.query_row(
            "SELECT COUNT(*) FROM resources", [], |row| row.get(0),
        )?;

        let mut stmt = self.conn.prepare(
            "SELECT category, COUNT(*) AS cnt FROM resources
             GROUP BY category ORDER BY cnt DESC",
        )?;
        let categories: Vec<CategoryCount> = stmt
            .query_map([], |row| Ok(CategoryCount { category: row.get(0)?, count: row.get(1)? }))?
            .collect::<Result<Vec<_>>>()?;

        let mut stmt = self.conn.prepare(
            "SELECT domain, COUNT(*) AS cnt FROM resources
             GROUP BY domain ORDER BY cnt DESC LIMIT 20",
        )?;
        let domains: Vec<DomainCount> = stmt
            .query_map([], |row| Ok(DomainCount { domain: row.get(0)?, count: row.get(1)? }))?
            .collect::<Result<Vec<_>>>()?;

        Ok(PrivacyStats { resource_count, categories, domains })
    }

    /// Delete all resources. Called by the Privacy Dashboard clear action.
    pub fn delete_all(&self) -> Result<usize> {
        self.conn.execute("DELETE FROM resources", [])
    }
}
