use rusqlite::{Connection, Result, params};
use serde::{Deserialize, Serialize};
use std::path::Path;

/// A single bookmark resource as stored in SQLCipher.
/// Fields match the schema defined in TS-0a-007 exactly.
/// url and title are stored encrypted; domain and category are stored in clear (D1).
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Resource {
    pub id: i64,
    pub uuid: String,
    pub url: String,
    pub title: String,
    pub domain: String,
    pub category: String,
}

/// A resource ready to be inserted — no id yet, uuid generated by caller.
#[derive(Debug, Deserialize)]
pub struct NewResource {
    pub uuid: String,
    pub url: String,
    pub title: String,
    pub domain: String,
    pub category: String,
}

pub struct Db {
    conn: Connection,
}

impl Db {
    /// Open (or create) the encrypted SQLCipher database at the given path.
    /// key is the passphrase used for AES encryption; it never leaves this process.
    pub fn open(path: &Path, key: &str) -> Result<Self> {
        let conn = Connection::open(path)?;
        conn.execute_batch(&format!("PRAGMA key = '{key}';"))?;
        conn.execute_batch("PRAGMA journal_mode = WAL;")?;
        Ok(Self { conn })
    }

    /// Create the `resources` table and its UUID index if they do not exist.
    /// Schema is the exact minimum defined in TS-0a-007 — no extra columns.
    pub fn migrate(&self) -> Result<()> {
        self.conn.execute_batch("
            CREATE TABLE IF NOT EXISTS resources (
                id       INTEGER PRIMARY KEY,
                uuid     TEXT    NOT NULL,
                url      TEXT    NOT NULL,
                title    TEXT    NOT NULL,
                domain   TEXT    NOT NULL,
                category TEXT    NOT NULL
            );
            CREATE UNIQUE INDEX IF NOT EXISTS idx_resources_uuid ON resources(uuid);
        ")
    }

    /// Insert a new resource. url and title must already be encrypted by the caller.
    pub fn insert_resource(&self, r: &NewResource) -> Result<i64> {
        self.conn.execute(
            "INSERT INTO resources (uuid, url, title, domain, category)
             VALUES (?1, ?2, ?3, ?4, ?5)",
            params![r.uuid, r.url, r.title, r.domain, r.category],
        )?;
        Ok(self.conn.last_insert_rowid())
    }

    /// Return all resources ordered by id (insertion order).
    pub fn all_resources(&self) -> Result<Vec<Resource>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, uuid, url, title, domain, category FROM resources ORDER BY id",
        )?;
        let rows = stmt.query_map([], |row| {
            Ok(Resource {
                id: row.get(0)?,
                uuid: row.get(1)?,
                url: row.get(2)?,
                title: row.get(3)?,
                domain: row.get(4)?,
                category: row.get(5)?,
            })
        })?;
        rows.collect()
    }

    /// Update the category of a resource identified by uuid.
    /// Used by the Classifier (T-0a-003) after domain classification.
    pub fn set_category(&self, uuid: &str, category: &str) -> Result<usize> {
        self.conn.execute(
            "UPDATE resources SET category = ?1 WHERE uuid = ?2",
            params![category, uuid],
        )
    }

    /// Return the number of stored resources.
    pub fn count(&self) -> Result<i64> {
        self.conn.query_row(
            "SELECT COUNT(*) FROM resources",
            [],
            |row| row.get(0),
        )
    }
}
